from .airplane_serializers import AirplaneSerializer
from .airplane_type_serializers import AirplaneTypeSerializer
from .airport_serializers import AirportSerializer
from .crew_serializers import CrewSerializer
from .flight_serializers import FlightSerializer, FlightListSerializer, FlightDetailSerializer
from .order_serializers import OrderSerializer
from .route_serializers import RouteSerializer, RouteListSerializer, RouteDetailSerializer
from .ticket_serializers import TicketSerializer, TicketListSerializer, TicketDetailSerializer
